In [1]:
import pandas as pd 
from pandas.api.types import is_string_dtype,is_numeric_dtype,is_categorical_dtype

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier

import numpy as np
from sklearn import metrics

In [2]:
data = pd.read_csv('Train.csv' , parse_dates=["saledate"])

C:\Users\Manish\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (13,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 53 columns):
SalesID                     401125 non-null int64
SalePrice                   401125 non-null int64
MachineID                   401125 non-null int64
ModelID                     401125 non-null int64
datasource                  401125 non-null int64
auctioneerID                380989 non-null float64
YearMade                    401125 non-null int64
MachineHoursCurrentMeter    142765 non-null float64
UsageBand                   69639 non-null object
saledate                    401125 non-null datetime64[ns]
fiModelDesc                 401125 non-null object
fiBaseModel                 401125 non-null object
fiSecondaryDesc             263934 non-null object
fiModelSeries               56908 non-null object
fiModelDescriptor           71919 non-null object
ProductSize                 190350 non-null object
fiProductClassDesc          401125 non-null object
state                       401125 non-null object
ProductGroup                401125 non-null object
ProductGroupDesc            401125 non-null object
Drive_System                104361 non-null object
Enclosure                   400800 non-null object
Forks                       192077 non-null object
Pad_Type                    79134 non-null object
Ride_Control                148606 non-null object
Stick                       79134 non-null object
Transmission                183230 non-null object
Turbocharged                79134 non-null object
Blade_Extension             25219 non-null object
Blade_Width                 25219 non-null object
Enclosure_Type              25219 non-null object
Engine_Horsepower           25219 non-null object
Hydraulics                  320570 non-null object
Pushblock                   25219 non-null object
Ripper                      104137 non-null object
Scarifier                   25230 non-null object
Tip_Control                 25219 non-null object
Tire_Size                   94718 non-null object
Coupler                     213952 non-null object
Coupler_System              43458 non-null object
Grouser_Tracks              43362 non-null object
Hydraulics_Flow             43362 non-null object
Track_Type                  99153 non-null object
Undercarriage_Pad_Width     99872 non-null object
Stick_Length                99218 non-null object
Thumb                       99288 non-null object
Pattern_Changer             99218 non-null object
Grouser_Type                99153 non-null object
Backhoe_Mounting            78672 non-null object
Blade_Type                  79833 non-null object
Travel_Controls             79834 non-null object
Differential_Type           69411 non-null object
Steering_Controls           69369 non-null object
dtypes: datetime64[ns](1), float64(2), int64(6), object(44)
memory usage: 162.2+ MB

In [5]:
data.isnull().sum()

SalesID                          0
SalePrice                        0
MachineID                        0
ModelID                          0
datasource                       0
auctioneerID                 20136
YearMade                         0
MachineHoursCurrentMeter    258360
UsageBand                   331486
saledate                         0
fiModelDesc                      0
fiBaseModel                      0
fiSecondaryDesc             137191
fiModelSeries               344217
fiModelDescriptor           329206
ProductSize                 210775
fiProductClassDesc               0
state                            0
ProductGroup                     0
ProductGroupDesc                 0
Drive_System                296764
Enclosure                      325
Forks                       209048
Pad_Type                    321991
Ride_Control                252519
Stick                       321991
Transmission                217895
Turbocharged                321991
Blade_Extension             375906
Blade_Width                 375906
Enclosure_Type              375906
Engine_Horsepower           375906
Hydraulics                   80555
Pushblock                   375906
Ripper                      296988
Scarifier                   375895
Tip_Control                 375906
Tire_Size                   306407
Coupler                     187173
Coupler_System              357667
Grouser_Tracks              357763
Hydraulics_Flow             357763
Track_Type                  301972
Undercarriage_Pad_Width     301253
Stick_Length                301907
Thumb                       301837
Pattern_Changer             301907
Grouser_Type                301972
Backhoe_Mounting            322453
Blade_Type                  321292
Travel_Controls             321291
Differential_Type           331714
Steering_Controls           331756
dtype: int64

In [6]:
data.describe()

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter
count,4.011250e+05,401125.000000,4.011250e+05,401125.000000,401125.000000,380989.000000,401125.000000,1.427650e+05
mean,1.919713e+06,31099.712848,1.217903e+06,6889.702980,134.665810,6.556040,1899.156901,3.457955e+03
std,9.090215e+05,23036.898502,4.409920e+05,6221.777842,8.962237,16.976779,291.797469,2.759026e+04
min,1.139246e+06,4750.000000,0.000000e+00,28.000000,121.000000,0.000000,1000.000000,0.000000e+00
25%,1.418371e+06,14500.000000,1.088697e+06,3259.000000,132.000000,1.000000,1985.000000,0.000000e+00
50%,1.639422e+06,24000.000000,1.279490e+06,4604.000000,132.000000,2.000000,1995.000000,0.000000e+00
75%,2.242707e+06,40000.000000,1.468067e+06,8724.000000,136.000000,4.000000,2000.000000,3.025000e+03
max,6.333342e+06,142000.000000,2.486330e+06,37198.000000,172.000000,99.000000,2013.000000,2.483300e+06

In [7]:
data.drop(['SalesID', 'MachineID' , 'ModelID', 'auctioneerID', 'datasource'] , axis =1 , inplace = True)

In [8]:
data.nunique()

SalePrice                     899
YearMade                       72
MachineHoursCurrentMeter    15152
UsageBand                       3
saledate                     3919
fiModelDesc                  4999
fiBaseModel                  1950
fiSecondaryDesc               175
fiModelSeries                 128
fiModelDescriptor             139
ProductSize                     6
fiProductClassDesc             74
state                          53
ProductGroup                    6
ProductGroupDesc                6
Drive_System                    4
Enclosure                       6
Forks                           2
Pad_Type                        4
Ride_Control                    3
Stick                           2
Transmission                    8
Turbocharged                    2
Blade_Extension                 2
Blade_Width                     6
Enclosure_Type                  3
Engine_Horsepower               2
Hydraulics                     12
Pushblock                       2
Ripper                          4
Scarifier                       2
Tip_Control                     3
Tire_Size                      17
Coupler                         3
Coupler_System                  2
Grouser_Tracks                  2
Hydraulics_Flow                 3
Track_Type                      2
Undercarriage_Pad_Width        19
Stick_Length                   29
Thumb                           3
Pattern_Changer                 3
Grouser_Type                    3
Backhoe_Mounting                2
Blade_Type                     10
Travel_Controls                 7
Differential_Type               4
Steering_Controls               5
dtype: int64

In [9]:
#data.drop(['MachineHoursCurrentMeter','fiModelDesc','fiBaseModel','fiSecondaryDesc','fiModelSeries','fiModelDescriptor','fiProductClassDesc','state','ProductGroupDesc'] ,axis =1, inplace = True)

In [10]:
data.head()

,SalePrice,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,66000,2004,68.0,Low,2006-11-16,521D,521,D,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,57000,1996,4640.0,Low,2004-03-26,950FII,950,F,II,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,10000,2001,2838.0,High,2004-02-26,226,226,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38500,2001,3486.0,High,2011-05-19,PC120-6E,PC120,NaN,-6E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11000,2007,722.0,Medium,2009-07-23,S175,S175,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Check Point

In [12]:
df = data
df.head(6)

,SalePrice,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,66000,2004,68.0,Low,2006-11-16,521D,521,D,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,57000,1996,4640.0,Low,2004-03-26,950FII,950,F,II,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,10000,2001,2838.0,High,2004-02-26,226,226,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38500,2001,3486.0,High,2011-05-19,PC120-6E,PC120,NaN,-6E,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11000,2007,722.0,Medium,2009-07-23,S175,S175,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,26500,2004,508.0,Low,2008-12-18,310G,310,G,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
data.isnull().count()
#df.fillna(df.median(), inplace = True)

SalePrice                   401125
YearMade                    401125
MachineHoursCurrentMeter    401125
UsageBand                   401125
saledate                    401125
fiModelDesc                 401125
fiBaseModel                 401125
fiSecondaryDesc             401125
fiModelSeries               401125
fiModelDescriptor           401125
ProductSize                 401125
fiProductClassDesc          401125
state                       401125
ProductGroup                401125
ProductGroupDesc            401125
Drive_System                401125
Enclosure                   401125
Forks                       401125
Pad_Type                    401125
Ride_Control                401125
Stick                       401125
Transmission                401125
Turbocharged                401125
Blade_Extension             401125
Blade_Width                 401125
Enclosure_Type              401125
Engine_Horsepower           401125
Hydraulics                  401125
Pushblock                   401125
Ripper                      401125
Scarifier                   401125
Tip_Control                 401125
Tire_Size                   401125
Coupler                     401125
Coupler_System              401125
Grouser_Tracks              401125
Hydraulics_Flow             401125
Track_Type                  401125
Undercarriage_Pad_Width     401125
Stick_Length                401125
Thumb                       401125
Pattern_Changer             401125
Grouser_Type                401125
Backhoe_Mounting            401125
Blade_Type                  401125
Travel_Controls             401125
Differential_Type           401125
Steering_Controls           401125
dtype: int64

In [14]:
df.isnull().sum()

SalePrice                        0
YearMade                         0
MachineHoursCurrentMeter    258360
UsageBand                   331486
saledate                         0
fiModelDesc                      0
fiBaseModel                      0
fiSecondaryDesc             137191
fiModelSeries               344217
fiModelDescriptor           329206
ProductSize                 210775
fiProductClassDesc               0
state                            0
ProductGroup                     0
ProductGroupDesc                 0
Drive_System                296764
Enclosure                      325
Forks                       209048
Pad_Type                    321991
Ride_Control                252519
Stick                       321991
Transmission                217895
Turbocharged                321991
Blade_Extension             375906
Blade_Width                 375906
Enclosure_Type              375906
Engine_Horsepower           375906
Hydraulics                   80555
Pushblock                   375906
Ripper                      296988
Scarifier                   375895
Tip_Control                 375906
Tire_Size                   306407
Coupler                     187173
Coupler_System              357667
Grouser_Tracks              357763
Hydraulics_Flow             357763
Track_Type                  301972
Undercarriage_Pad_Width     301253
Stick_Length                301907
Thumb                       301837
Pattern_Changer             301907
Grouser_Type                301972
Backhoe_Mounting            322453
Blade_Type                  321292
Travel_Controls             321291
Differential_Type           331714
Steering_Controls           331756
dtype: int64

In [15]:
def display_all(data):
    with pd.option_context("display.max_rows",100,"display.max_columns",200):
        display(data)

In [16]:
display_all(df)

,SalePrice,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Drive_System,Enclosure,Forks,Pad_Type,Ride_Control,Stick,Transmission,Turbocharged,Blade_Extension,Blade_Width,Enclosure_Type,Engine_Horsepower,Hydraulics,Pushblock,Ripper,Scarifier,Tip_Control,Tire_Size,Coupler,Coupler_System,Grouser_Tracks,Hydraulics_Flow,Track_Type,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,66000,2004,68.0,Low,2006-11-16,521D,521,D,NaN,NaN,NaN,Wheel Loader - 110.0 to 120.0 Horsepower,Alabama,WL,Wheel Loader,NaN,EROPS w AC,None or Unspecified,NaN,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 Valve,NaN,NaN,NaN,NaN,None or Unspecified,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,57000,1996,4640.0,Low,2004-03-26,950FII,950,F,II,NaN,Medium,Wheel Loader - 150.0 to 175.0 Horsepower,North Carolina,WL,Wheel Loader,NaN,EROPS w AC,None or Unspecified,NaN,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 Valve,NaN,NaN,NaN,NaN,23.5,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,10000,2001,2838.0,High,2004-02-26,226,226,NaN,NaN,NaN,NaN,Skid Steer Loader - 1351.0 to 1601.0 Lb Operat...,New York,SSL,Skid Steer Loaders,NaN,OROPS,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auxiliary,NaN,NaN,NaN,NaN,NaN,None or Unspecified,None or Unspecified,None or Unspecified,Standard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38500,2001,3486.0,High,2011-05-19,PC120-6E,PC120,NaN,-6E,NaN,Small,"Hydraulic Excavator, Track - 12.0 to 14.0 Metr...",Texas,TEX,Track Excavators,NaN,EROPS w AC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 Valve,NaN,NaN,NaN,NaN,NaN,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11000,2007,722.0,Medium,2009-07-23,S175,S175,NaN,NaN,NaN,NaN,Skid Steer Loader - 1601.0 to 1751.0 Lb Operat...,New York,SSL,Skid Steer Loaders,NaN,EROPS,None or Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auxiliary,NaN,NaN,NaN,NaN,NaN,None or Unspecified,None or Unspecified,None or Unspecified,Standard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,10500,2005,NaN,NaN,2011-11-02,35NX2,35,NX,2,NaN,Mini,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,NaN,EROPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auxiliary,NaN,NaN,NaN,NaN,NaN,None or Unspecified,NaN,NaN,NaN,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,11000,2005,NaN,NaN,2011-11-02,35NX2,35,NX,2,NaN,Mini,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,NaN,EROPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,NaN,NaN,NaN,NaN,NaN,None or Unspecified,NaN,NaN,NaN,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,11500,2005,NaN,NaN,2011-11-02,35NX2,35,NX,2,NaN,Mini,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...",Maryland,TEX,Track Excavators,NaN,EROPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Auxiliary,NaN,NaN,NaN,NaN,NaN,None or Unspecified,NaN,NaN,NaN,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,9000,2005,NaN,NaN,2011-10-25,30NX,30,NX,NaN,NaN,Mini,"Hydraulic Excavator, Track - 2.0 to 3.0 Metric...",Florida,TEX,Track Excavators,NaN,EROPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,NaN,NaN,NaN,NaN,NaN,None or Unspecified,NaN,NaN,NaN,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,7750,2005,NaN,NaN,2011-10-25,30NX,30,NX,NaN,NaN,Mini,"Hydraulic Excavator, Track - 2.0 to 3.0 Metric...",Florida,TEX,Track Excavators,NaN,EROPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,NaN,NaN,NaN,NaN,NaN,None or Unspecified,NaN,NaN,NaN,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [17]:
df.saledate.dt.year

0         2006
1         2004
2         2004
3         2011
4         2009
          ...
401120    2011
401121    2011
401122    2011
401123    2011
401124    2011
Name: saledate, Length: 401125, dtype: int64

In [18]:
df.YearMade

0         2004
1         1996
2         2001
3         2001
4         2007
          ...
401120    2005
401121    2005
401122    2005
401123    2005
401124    2005
Name: YearMade, Length: 401125, dtype: int64

In [19]:
df["Diffyear"] = df.saledate.dt.year - df.YearMade

In [20]:
df["Diffyear"].isnull().sum()

0

In [21]:
df.nunique()

SalePrice                     899
YearMade                       72
MachineHoursCurrentMeter    15152
UsageBand                       3
saledate                     3919
fiModelDesc                  4999
fiBaseModel                  1950
fiSecondaryDesc               175
fiModelSeries                 128
fiModelDescriptor             139
ProductSize                     6
fiProductClassDesc             74
state                          53
ProductGroup                    6
ProductGroupDesc                6
Drive_System                    4
Enclosure                       6
Forks                           2
Pad_Type                        4
Ride_Control                    3
Stick                           2
Transmission                    8
Turbocharged                    2
Blade_Extension                 2
Blade_Width                     6
Enclosure_Type                  3
Engine_Horsepower               2
Hydraulics                     12
Pushblock                       2
Ripper                          4
Scarifier                       2
Tip_Control                     3
Tire_Size                      17
Coupler                         3
Coupler_System                  2
Grouser_Tracks                  2
Hydraulics_Flow                 3
Track_Type                      2
Undercarriage_Pad_Width        19
Stick_Length                   29
Thumb                           3
Pattern_Changer                 3
Grouser_Type                    3
Backhoe_Mounting                2
Blade_Type                     10
Travel_Controls                 7
Differential_Type               4
Steering_Controls               5
Diffyear                      106
dtype: int64

In [22]:
columns = []

In [23]:
for i in df.columns: 
         if is_string_dtype(df[i]):
                columns.append(i)

In [24]:
columns

['UsageBand',
 'fiModelDesc',
 'fiBaseModel',
 'fiSecondaryDesc',
 'fiModelSeries',
 'fiModelDescriptor',
 'ProductSize',
 'fiProductClassDesc',
 'state',
 'ProductGroup',
 'ProductGroupDesc',
 'Drive_System',
 'Enclosure',
 'Forks',
 'Pad_Type',
 'Ride_Control',
 'Stick',
 'Transmission',
 'Turbocharged',
 'Blade_Extension',
 'Blade_Width',
 'Enclosure_Type',
 'Engine_Horsepower',
 'Hydraulics',
 'Pushblock',
 'Ripper',
 'Scarifier',
 'Tip_Control',
 'Tire_Size',
 'Coupler',
 'Coupler_System',
 'Grouser_Tracks',
 'Hydraulics_Flow',
 'Track_Type',
 'Undercarriage_Pad_Width',
 'Stick_Length',
 'Thumb',
 'Pattern_Changer',
 'Grouser_Type',
 'Backhoe_Mounting',
 'Blade_Type',
 'Travel_Controls',
 'Differential_Type',
 'Steering_Controls']

In [25]:
df.drop(['YearMade'] , axis = 1 , inplace = True)
df.drop(['saledate'] , axis = 1 , inplace = True)

In [26]:
def fixmissing(df,col):
    if is_numeric_dtype(df[col]):
        df[col]=df[col].fillna(df[col].median())
            
def numericalize(df,col):
    if not is_numeric_dtype(df[col]):
        df[col]=pd.Categorical(df[col]).codes+1

In [27]:
for col in df.columns:
    numericalize(df,col)
    fixmissing(df,col)

In [28]:
df.head()

,SalePrice,MachineHoursCurrentMeter,UsageBand,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,...,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,Diffyear
0,66000,68.0,2,950,296,41,0,0,0,59,...,0,0,0,0,0,0,0,4,2,2
1,57000,4640.0,2,1725,527,55,104,0,4,62,...,0,0,0,0,0,0,0,4,2,8
2,10000,2838.0,1,331,110,0,0,0,0,39,...,0,0,0,0,0,0,0,0,0,3
3,38500,3486.0,1,3674,1375,0,51,0,6,8,...,0,0,0,0,0,0,0,0,0,10
4,11000,722.0,3,4208,1529,0,0,0,0,40,...,0,0,0,0,0,0,0,0,0,2

In [29]:
display_all(df)

,SalePrice,MachineHoursCurrentMeter,UsageBand,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Drive_System,Enclosure,Forks,Pad_Type,Ride_Control,Stick,Transmission,Turbocharged,Blade_Extension,Blade_Width,Enclosure_Type,Engine_Horsepower,Hydraulics,Pushblock,Ripper,Scarifier,Tip_Control,Tire_Size,Coupler,Coupler_System,Grouser_Tracks,Hydraulics_Flow,Track_Type,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls,Diffyear
0,66000,68.0,2,950,296,41,0,0,0,59,1,6,6,0,3,1,0,2,0,0,0,0,0,0,0,1,0,0,0,0,17,3,0,0,0,0,0,0,0,0,0,0,0,0,4,2,2
1,57000,4640.0,2,1725,527,55,104,0,4,62,33,6,6,0,3,1,0,2,0,0,0,0,0,0,0,1,0,0,0,0,12,3,0,0,0,0,0,0,0,0,0,0,0,0,4,2,8
2,10000,2838.0,1,331,110,0,0,0,0,39,32,3,3,0,6,1,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,3,1,1,3,0,0,0,0,0,0,0,0,0,0,0,3
3,38500,3486.0,1,3674,1375,0,51,0,6,8,44,4,4,0,3,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10
4,11000,722.0,3,4208,1529,0,0,0,0,40,32,3,3,0,1,1,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,3,1,1,3,0,0,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,10500,0.0,0,657,207,106,69,0,5,17,20,4,4,0,1,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,3,0,0,0,2,19,29,3,2,1,0,0,0,0,0,6
401121,11000,0.0,0,657,207,106,69,0,5,17,20,4,4,0,1,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,3,0,0,0,2,19,29,3,2,1,0,0,0,0,0,6
401122,11500,0.0,0,657,207,106,69,0,5,17,20,4,4,0,1,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,3,0,0,0,2,19,29,3,2,1,0,0,0,0,0,6
401123,9000,0.0,0,483,159,106,0,0,5,13,9,4,4,0,1,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,3,0,0,0,2,19,29,3,2,1,0,0,0,0,0,6
401124,7750,0.0,0,483,159,106,0,0,5,13,9,4,4,0,1,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,3,0,0,0,2,19,29,3,2,1,0,0,0,0,0,6

In [30]:
X = df.drop(['SalePrice'] , axis = 1)
Y = df['SalePrice']

In [31]:
x_train , x_test , y_train , y_test = train_test_split(X,Y,train_size = 0.8)

In [32]:

x_train.shape , x_test.shape , y_train.shape , y_test.shape

((320900, 46), (80225, 46), (320900,), (80225,))

In [33]:
final_Train = pd.DataFrame(x_train)

In [34]:
model2 = RandomForestRegressor(n_estimators=20)
model2.fit(x_train , y_train)
predictions = model2.predict(x_test)

In [35]:
model2.score(x_train,y_train)

0.9737015960014851

In [36]:
y_pred = model2.predict(x_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 5180.628816202073
Mean Squared Error: 67246334.65020819
Root Mean Squared Error: 8200.38625006214